# the service for mcdep deployment
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  selector:
    app: vpromc  # label of pods that this service serves
  ports:
    - port: 11211
      targetPort: vpromc-port
      protocol: TCP
  type: ClusterIP
