apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: vprofile/vprofiledb:V1
        ports:
          - name: vprodb-port
            containerPort: 3306  # the default port for msql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db-pass
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      nodeSelector:
        zone: us-east-1a  # this pod only runs in the nodes in this zone
